// <auto-generated />
namespace TechPush.Infrastructure.Migrations.CMS
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EntityModifications : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EntityModifications));
        
        string IMigrationMetadata.Id
        {
            get { return "201901181348046_EntityModifications"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
